services:
    backend:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        image: vgr-quiz/backend:latest
        container_name: backend
        restart: always
        networks:
            - appnet
        ports:
            - ${APP_PORT}:80
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
#    node:
#        build:
#            context: ./docker/node
#            dockerfile: Dockerfile
#        image: vgr-quiz/node:latest
#        networks:
#            - appnet
#        volumes:
#            -   .:/opt
#        working_dir: /opt
#        command: echo "Node container is running"
    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        networks:
            - appnet
        volumes:
            -  cachedata:/data
    db:
        image: mysql:8.4
        container_name: mysql
        networks:
            - appnet
        ports:
            -   ${DB_PORT_FORWARD}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
networks:
    appnet:
        driver: bridge
volumes:
    dbdata:
        driver: local
    cachedata:
        driver: local

